# Generated by Django 4.0.6 on 2022-07-21 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='borrowed_books',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
