version: '3.9'

services:
  postgres:
    image: postgres:14.4-alpine
    ports: 
      - 5432:5432
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  migration:
    build: .
    env_file:
      - ./.env
    environment:
      - COMPOSE=true
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py migrate'
    depends_on:
      postgres: 
        condition: service_healthy

  django:
    build: .
    env_file:
      - ./.env
    environment:
      - COMPOSE=true
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    depends_on:
      - migration
    ports:
      - 8000:8000
    