# Generated by Django 4.0.6 on 2022-07-21 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('review', models.TextField()),
                ('recommendation', models.CharField(max_length=50)),
                ('type_review', models.CharField(choices=[('Critique', 'Critique'), ('Summary', 'Summary'), ('Recommendation', 'Recommendation')], default='Summary', max_length=32)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='books.book')),
            ],
        ),
    ]
