# Generated by Django 4.0.6 on 2022-07-20 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateField(default=datetime.timedelta(days=30)),
        ),
    ]
