# Generated by Django 4.0.6 on 2022-07-20 19:45

from django.db import migrations, models
import loans.models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='return_date',
            field=models.DateTimeField(default=loans.models.return_date),
        ),
    ]
